name: Build LaTeX HTML and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-science
        sudo apt-get install -y python3-pygments
        sudo apt-get install -y make
        sudo apt-get install -y latex2html

    - name: Convert LaTeX to HTML
      run: |
        mkdir output
        latex2html -dir output main.tex

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./output
        external_repository: ULB-MachineLearningGroup/INFO-F305
        publish_branch: gh-pages
